// Service worker for the World Cup 2026 forecast PWA.
//
// Strategy:
//   - Static app shell (HTML/CSS/JS/ESM modules + data JSON + icons) is
//     precached on install so the app launches fully offline.
//   - /api/live is network-first with a cache fallback, so a flaky
//     connection during the tournament still shows the last live snapshot.
//   - Everything else same-origin is cache-first, network-fallback.
//
// Bump VERSION on any shell change to invalidate the old cache bucket.
// The worker itself is served with no-cache (see vercel.json) so clients
// always re-check it and pick up a new VERSION promptly.

const VERSION = "wc26-v21";

// Files that definitely exist in the repo. market-snapshot.json is
// intentionally omitted — it's generated by the scrape cron, loaded with
// cache:"no-store", and falls back to a baked-in constant when absent, so
// precaching it would risk an atomic addAll() failure on a fresh deploy.
const SHELL = [
  "./",
  "index.html",
  "styles.css",
  "app.js",
  "vendor/supabase.js",
  "predictor.js",
  "data.js",
  "rng.js",
  "models/covariates.js",
  "models/dixonColes.js",
  "models/elo.js",
  "models/ensemble.js",
  "models/market.js",
  "models/matchForecast.js",
  "models/markets.js",
  "models/poisson.js",
  "models/players.js",
  "models/squad.js",
  "data/historical-matches.js",
  "data/players-2026.js",
  "data/team-bases.js",
  "data/venues-2026.js",
  "data/schedule-2026.json",
  "data/title-history.json",
  "data/player-props-2026.json",
  "data/freshness.json",
  "favicon.svg",
  "manifest.webmanifest",
  "icon-192.png",
  "icon-512.png",
  "apple-touch-icon.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(VERSION).then(async (cache) => {
      // Add each entry independently so one missing/404 file (e.g. a data
      // JSON not yet generated on a fresh deploy) doesn't abort the whole
      // install the way a single atomic addAll() would.
      await Promise.all(
        SHELL.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch(() => {}),
        ),
      );
      self.skipWaiting();
    }),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))),
    ).then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);

  // Only handle our own origin; let cross-origin requests pass through.
  if (url.origin !== self.location.origin) return;

  // Live API: network-first, fall back to the last cached snapshot offline.
  if (url.pathname.endsWith("/api/live")) {
    event.respondWith(
      fetch(request)
        .then((resp) => {
          const copy = resp.clone();
          caches.open(VERSION).then((cache) => cache.put(request, copy));
          return resp;
        })
        .catch(() => caches.match(request)),
    );
    return;
  }

  // /api/config.js carries runtime env vars (Supabase URL + anon key).
  // Never cache it — otherwise an env change requires every user to
  // manually clear their service worker.
  if (url.pathname.endsWith("/api/config.js")) {
    event.respondWith(fetch(request));
    return;
  }

  // Everything else same-origin: cache-first, network-fallback, and
  // populate the cache on the way so runtime assets (e.g. the scraped
  // market snapshot) become available offline after the first online load.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((resp) => {
          if (resp.ok && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(VERSION).then((cache) => cache.put(request, copy));
          }
          return resp;
        })
        .catch(() => cached);
    }),
  );
});
